server:
  port: 8080
  servlet:
    session:
      timeout: 600s
spring:
  application:
    name: boot-layui-demo
  security:
    user:
      name: zhaolei
      password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
auth:
  skip:
    antMatchers:
      /**/favicon.ico,
      /swagger-resources/**,
      /webjars/**,
      /v2/**,
      /swagger-ui.html/**,
      /sysUser/**,
      /login